# Generated by Django 6.0.4 on 2026-04-24 18:20

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bull',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=32, unique=True, verbose_name='Полный номер')),
                ('biavka_part', models.CharField(max_length=8, verbose_name='Бивайка (первые 8 символов)')),
                ('bull_number', models.CharField(max_length=6, verbose_name='Номер быка (последние 6 символов)')),
                ('is_active', models.BooleanField(default=True, help_text='Если выключено, бык считается выбывшим.', verbose_name='На площадке')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'ordering': ['bull_number'],
            },
        ),
        migrations.CreateModel(
            name='ExcelImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружено')),
                ('previous_weighing_date', models.DateField(verbose_name='Дата предыдущего взвешивания')),
                ('current_weighing_date', models.DateField(verbose_name='Дата текущего взвешивания')),
                ('total_rows', models.PositiveIntegerField(default=0, verbose_name='Строк в файле')),
                ('applied_rows', models.PositiveIntegerField(default=0, verbose_name='Применено строк')),
                ('pending_rows', models.PositiveIntegerField(default=0, verbose_name='Требуют сопоставления')),
            ],
        ),
        migrations.CreateModel(
            name='DepartureEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departed_at', models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата выбытия')),
                ('reason', models.CharField(choices=[('MEAT_PLANNED', 'Планово на мясокомбинат'), ('EMERGENCY_SLAUGHTER', 'Срочно на убой'), ('OTHER', 'Другое')], max_length=32, verbose_name='Маркер выбытия')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('bull', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='departure', to='herd.bull', verbose_name='Бык')),
            ],
            options={
                'ordering': ['-departed_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ExcelImportPendingRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_external_id', models.CharField(max_length=32, verbose_name='Номер из файла')),
                ('previous_weight_kg', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Предыдущий вес, кг')),
                ('current_weight_kg', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Текущий вес, кг')),
                ('suggested_ids', models.JSONField(default=list, help_text='Список предложенных системой совпадений.', verbose_name='Похожие номера')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Сопоставлено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_items', to='herd.excelimportbatch', verbose_name='Пакет импорта')),
                ('resolved_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_import_rows', to='herd.bull', verbose_name='Выбранный бык')),
            ],
            options={
                'ordering': ['is_resolved', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('LEFT', 'Левая'), ('RIGHT', 'Правая')], max_length=5, verbose_name='Сторона')),
                ('order', models.PositiveSmallIntegerField(verbose_name='Порядковый номер в ряду')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='Название секции')),
                ('capacity', models.PositiveSmallIntegerField(default=150, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Вместимость')),
            ],
            options={
                'ordering': ['side', 'order'],
                'constraints': [models.UniqueConstraint(fields=('side', 'order'), name='unique_side_order')],
            },
        ),
        migrations.AddField(
            model_name='bull',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bulls', to='herd.section', verbose_name='Текущая секция'),
        ),
        migrations.CreateModel(
            name='SectionMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moved_at', models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата перемещения')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('bull', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='herd.bull', verbose_name='Бык')),
                ('from_section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements_from', to='herd.section', verbose_name='Из секции')),
                ('to_section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements_to', to='herd.section', verbose_name='В секцию')),
            ],
            options={
                'ordering': ['-moved_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='WeightRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weighing_date', models.DateField(verbose_name='Дата взвешивания')),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Вес, кг')),
                ('source', models.CharField(choices=[('excel', 'Excel'), ('manual', 'Ручной ввод')], default='manual', max_length=16, verbose_name='Источник')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('bull', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_records', to='herd.bull', verbose_name='Бык')),
            ],
            options={
                'ordering': ['-weighing_date', '-id'],
                'constraints': [models.UniqueConstraint(fields=('bull', 'weighing_date', 'source'), name='unique_weight_for_bull_date_source')],
            },
        ),
    ]
