# Generated by Django 6.0.4 on 2026-04-26 08:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bull',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bivayka', models.CharField(max_length=8)),
                ('bull_number', models.CharField(max_length=6)),
                ('full_code', models.CharField(max_length=14, unique=True)),
                ('arrival_date', models.DateField(default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('ACTIVE', 'На площадке'), ('DEPARTED', 'Выбыл')], default='ACTIVE', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Бык',
                'verbose_name_plural': 'Быки',
                'ordering': ['bull_number'],
            },
        ),
        migrations.CreateModel(
            name='ImportSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_name', models.CharField(max_length=255)),
                ('processed_rows', models.PositiveIntegerField(default=0)),
                ('created_records', models.PositiveIntegerField(default=0)),
                ('updated_records', models.PositiveIntegerField(default=0)),
                ('unresolved_rows', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Сессия импорта',
                'verbose_name_plural': 'Сессии импорта',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(unique=True)),
                ('side', models.CharField(choices=[('LEFT', 'Левая сторона'), ('RIGHT', 'Правая сторона')], max_length=5)),
                ('position_in_row', models.PositiveSmallIntegerField()),
                ('capacity', models.PositiveIntegerField(default=150)),
            ],
            options={
                'verbose_name': 'Секция',
                'verbose_name_plural': 'Секции',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='DepartureRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_date', models.DateField()),
                ('weight_kg', models.PositiveIntegerField()),
                ('marker', models.CharField(choices=[('MEAT_PLANT', 'На мясокомбинат'), ('URGENT_SLAUGHTER', 'Срочная отправка на убой'), ('OTHER', 'Другое')], max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bull', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='departure', to='bulls.bull')),
            ],
            options={
                'verbose_name': 'Выбытие',
                'verbose_name_plural': 'Выбытия',
                'ordering': ['-departure_date', 'bull__bull_number'],
            },
        ),
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField(default=django.utils.timezone.localdate)),
                ('record_type', models.CharField(choices=[('INJECTION', 'Укол'), ('ILLNESS', 'Болезнь'), ('OBSERVATION', 'Наблюдение')], max_length=20)),
                ('description', models.TextField()),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bull', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='bulls.bull')),
            ],
            options={
                'verbose_name': 'Запись о здоровье',
                'verbose_name_plural': 'Записи о здоровье',
                'ordering': ['-record_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incoming_bivayka', models.CharField(max_length=8)),
                ('incoming_bull_number', models.CharField(max_length=6)),
                ('incoming_full_code', models.CharField(max_length=14)),
                ('weighing_date', models.DateField()),
                ('weight_kg', models.PositiveIntegerField()),
                ('suggested_full_codes', models.JSONField(blank=True, default=list)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_bull', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_import_issues', to='bulls.bull')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='bulls.importsession')),
            ],
            options={
                'verbose_name': 'Проблема импорта',
                'verbose_name_plural': 'Проблемы импорта',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='bull',
            name='current_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bulls', to='bulls.section'),
        ),
        migrations.CreateModel(
            name='SectionTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_date', models.DateField()),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bull', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='bulls.bull')),
                ('from_section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transfers', to='bulls.section')),
                ('to_section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfers', to='bulls.section')),
            ],
            options={
                'verbose_name': 'Перевод между секциями',
                'verbose_name_plural': 'Переводы между секциями',
                'ordering': ['-transfer_date', 'bull__bull_number'],
            },
        ),
        migrations.CreateModel(
            name='WeightRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weighing_date', models.DateField()),
                ('weight_kg', models.PositiveIntegerField()),
                ('source', models.CharField(choices=[('MANUAL', 'Ручной ввод'), ('EXCEL', 'Импорт Excel')], default='MANUAL', max_length=10)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bull', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_records', to='bulls.bull')),
            ],
            options={
                'verbose_name': 'Запись взвешивания',
                'verbose_name_plural': 'Записи взвешивания',
                'ordering': ['-weighing_date', 'bull__bull_number'],
            },
        ),
        migrations.AddConstraint(
            model_name='bull',
            constraint=models.UniqueConstraint(fields=('bivayka', 'bull_number'), name='unique_bivayka_and_bull_number'),
        ),
        migrations.AddConstraint(
            model_name='weightrecord',
            constraint=models.UniqueConstraint(fields=('bull', 'weighing_date'), name='unique_bull_weighing_per_date'),
        ),
    ]
