# Generated by Django 6.0.4 on 2026-04-26 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulls', '0002_seed_sections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bull',
            name='full_code',
            field=models.CharField(blank=True, max_length=14, unique=True),
        ),
    ]
